### ISSUE TITLE
Отсутствие запаха грубого секса

### ISSUE THREAD

**Issue by FREEDINN3R** [xSpleet/Magpie#1]
При установке двух кактусов в угол подвала, не появляется запах грубого секса. Версия 1.19.3 Fabric.
Что должно было произойти: запах грубого секса.
Что происходит: отсутствие запаха грубого секса.
Возможный фикс: добавить запах грубого секса.

**Comment by redfox193** [comment]
Да, всё действительно так.
Я столкнулся с этой проблемой, когда хотел проверить совместимость моего мода с монашками в подвале с запахом грубого секса.
Возможно, я не совсем понимаю, но поймите меня, пожалуйста.

If you don't speak Russian:
Yes, that's true.
I ran into this problem when I wanted to test the compatibility of my mod with nuns in a basement with the smell of rough sex.
I may not fully understand, but please understand me

Спасибо (Thank you)

**Comment by xSpleet** [comment]
Thanks, I will look into this later

**Comment by redfox193** [comment]
> Thanks, I will look into this later

How long?
