### ISSUE TITLE
[Request]: More Versions 

### ISSUE THREAD

**Issue by VanCock** [xSpleet/Magpie#2]
Your mod is quite cool, I like the idea of providing flight only in specific conditions, and even tho assets could most definitely be improved I still strongly believe this mod will get some attention, tho do you plan to release support for other versions, preferably 1.20.1, of course it's fine if you don't want to, it's still worth asking,
Cheers.  :)

**Comment by xSpleet** [comment]
Thanks for the nice words! I was planning to add support for more versions, as well as more features and better assets, so stay tuned for that!

**Comment by xSpleet** [comment]
The versions are on their way! The main part is done, they are going to be tested now, so It shouldn't take more than a week! Support for 1.19.4, 1.20, 1.20.1 and 1.20.2 is going to be added!

**Comment by xSpleet** [comment]
The new versions are now available on modrinth and should be available on curseforge soon!
