### ISSUE TITLE
Usage of Screen in common environment

### ISSUE THREAD

**Issue by Jamalam360** [xSpleet/Magpie#3]
Hi, fellow mod dev here so I'll just cut to the chase :laughing: 

You are loading the `Screen` class [here](https://github.com/xSpleet/Magpie/blob/e121a49149a6d2775f82c5dd637ec13a302de73c/src/main/java/xspleet/magpie/mixin/MixinLivingEntity.java#L48) in a common environment, which means the mod crashes on servers since `Screen` doesn't exist there.

I can't remember the exact name of the field or which class it belongs to, but I am almost certain that one of the entity classes stores whether it is sneaking (probably `PlayerEntity` or a subclass), so you should probably use that instead.

**Comment by xSpleet** [comment]
Okey, thanks, I’ll look into this!

**Comment by xSpleet** [comment]
I tested the mod on 1.19.4 paper and it seems to be fine, what version where you testing it on
It's pretty weird, because I could start a server, and the other issue seems to lead to the same issue with the mod, but I can't reproduce it... Strange...

**Comment by Jamalam360** [comment]
1.20.1 Fabric

**Comment by xSpleet** [comment]
Ok, got it
I just was able to reproduce it, but just on the clinet, not a server
There seems to also be a problem with TrinketsAPI so I will have to investigate

**Comment by xSpleet** [comment]
Hi
I fixed the issue and now the new versions are uploaded!
